-- create_db.sql
-- Run this to build the schema for the Ride-Sharing Demand & Pricing Database

DROP TABLE IF EXISTS TRIP;
DROP TABLE IF EXISTS SURGE_PERIOD;
DROP TABLE IF EXISTS ZONE;
DROP TABLE IF EXISTS TELEMATICS_TRACKER;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS DISPATCH_BASE;

CREATE TABLE DISPATCH_BASE (
    BaseCode VARCHAR(10) PRIMARY KEY,
    BaseName VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICLE (
    VehicleID VARCHAR(15) PRIMARY KEY,
    LicensePlate VARCHAR(10) UNIQUE NOT NULL,
    BaseCode VARCHAR(10),
    FOREIGN KEY (BaseCode) REFERENCES DISPATCH_BASE(BaseCode)
);

CREATE TABLE TELEMATICS_TRACKER (
    TrackerID VARCHAR(15) PRIMARY KEY,
    FirmwareVersion VARCHAR(20),
    VehicleID VARCHAR(15) UNIQUE,
    FOREIGN KEY (VehicleID) REFERENCES VEHICLE(VehicleID)
);

CREATE TABLE ZONE (
    ZoneID INT PRIMARY KEY,
    Borough VARCHAR(50) NOT NULL
);

CREATE TABLE SURGE_PERIOD (
    ZoneID INT,
    StartTime DATETIME,
    SurgeMultiplier DECIMAL(3,2) NOT NULL,
    PRIMARY KEY (ZoneID, StartTime),
    FOREIGN KEY (ZoneID) REFERENCES ZONE(ZoneID)
);

CREATE TABLE TRIP (
    TripID INT PRIMARY KEY,
    PickupTime DATETIME NOT NULL,
    DropoffTime DATETIME,
    FareAmount DECIMAL(6,2),
    VehicleID VARCHAR(15),
    ZoneID INT,
    FOREIGN KEY (VehicleID) REFERENCES VEHICLE(VehicleID),
    FOREIGN KEY (ZoneID) REFERENCES ZONE(ZoneID)
);